export const SET_HAND_RAISED = "SET_HAND_RAISED";
export const SET_AUDIO_MUTED = "SET_AUDIO_MUTED";
export const SET_VIDEO_MUTED = "SET_VIDEO_MUTED";
export const SET_UNMUTE_ALLOWED = "SET_UNMUTE_ALLOWED";
export const SET_IS_MULTISTREAM = "SET_IS_MULTISTREAM";
export const SET_REMOTE_SHARE_ACTIVE = "SET_REMOTE_SHARE_ACTIVE";
export const SET_MEETING_STATUS = "SET_MEETING_STATUS";
export const SET_ACTIVE_SPEAKERS = "SET_ACTIVE_SPEAKERS";
export const SET_MEMBERS = "SET_MEMBERS";
export const UPDATE_MEMBERS = "UPDATE_MEMBERS";
export const ADD_MEMBERS = "ADD_MEMBERS";
export const REMOVE_MEMBERS = "REMOVE_MEMBERS";

export const SET_LOCAL_MEDIA = "SET_LOCAL_MEDIA";
export const SET_REMOTE_MEDIA = "SET_REMOTE_MEDIA";
export const SET_MULTISTREAM_VIDEO = "SET_MULTISTREAM_VIDEO";
export const SET_MULTISTREAM_VIDEO_GROUP = "SET_MULTISTREAM_VIDEO_GROUP";
export const SET_MULTISTREAM_VIDEO_PANE = "SET_MULTISTREAM_VIDEO_PANE";
export const CLEAR_MULTISTREAM_VIDEO = "CLEAR_MULTISTREAM_VIDEO";

export const JOIN_MEETING = "JOIN_MEETING";
export const LEAVE_MEETING = "LEAVE_MEETING";

export const SET_MEETING_JOIN = "SET_MEETING_JOIN";

export const SET_ALERT_LEAVE_MEETING = "SET_ALERT_LEAVE_MEETING";
export const SET_ALERT_ENTER_PASSWORD = "SET_ALERT_ENTER_PASSWORD";
export const SET_ALERT_ENTER_CAPTCHA = "SET_ALERT_ENTER_CAPTCHA";
export const SET_OVERLAY = "SET_OVERLAY";
export const SET_MEETING_CAPTCHA = "SET_MEETING_CAPTCHA";

export const SET_CONTROL_PANEL = "SET_CONTROL_PANEL";
export const SET_DTMF_PANEL = "SET_DTMF_PANEL";

export const GET_MEDIA_DEVICES_SUCCESS = "GET_MEDIA_DEVICES_SUCCESS";
export const GET_MEDIA_DEVICES_FAILED = "GET_MEDIA_DEVICES_FAILED";

export const SET_VIEW_PORT = "SET_VIEW_PORT";
