export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const WEBEX_BEGIN_API_CALL = "WEBEX_BEGIN_API_CALL";
export const WEBEX_API_CALL_ERROR = "WEBEX_API_CALL_ERROR";
export const WEBEX_API_CALL_SUCCESS = "WEBEX_API_CALL_SUCCESS";

export const WEBEX_LOGIN_SUCCESS = "WEBEX_LOGIN_SUCCESS";
export const WEBEX_LOGIN_FAILED = "WEBEX_LOGIN_FAILED";
export const WEBEX_LOGOUT_SUCCESS = "WEBEX_LOGOUT_SUCCESS";

export const WEBEX_GET_MEETINGS_SUCCESS = "WEBEX_GET_MEETINGS_SUCCESS";
export const WEBEX_GET_MEETINGS_FAILED = "WEBEX_GET_MEETINGS_FAILED";
export const WEBEX_CREATE_MEETING_SUCCESS = "WEBEX_CREATE_MEETING_SUCCESS";
export const WEBEX_CREATE_MEETING_FAILED = "WEBEX_CREATE_MEETING_FAILED";
export const WEBEX_DELETE_MEETING_SUCCESS = "WEBEX_DELETE_MEETING_SUCCESS";
export const WEBEX_DELETE_MEETING_FAILED = "WEBEX_DELETE_MEETING_FAILED";
export const WEBEX_UPDATE_MEETING_SUCCESS = "WEBEX_UPDATE_MEETING_SUCCESS";
export const WEBEX_UPDATE_MEETING_FAILED = "WEBEX_UPDATE_MEETING_FAILED";

export const SET_AUDIO_DEVICE_INPUT = "SET_AUDIO_DEVICE_INPUT";
export const SET_AUDIO_DEVICE_OUTPUT = "SET_AUDIO_DEVICE_OUTPUT";
export const SET_VIDEO_DEVICE_INPUT = "SET_VIDEO_DEVICE_INPUT";
export const SET_VIDEO_DEVICE_QUALITY = "SET_VIDEO_DEVICE_QUALITY";
export const SET_AUDIO_NOISE_REMOVAL = "SET_AUDIO_NOISE_REMOVAL";
export const SET_VIRTUAL_BACKGROUND_MODE = "SET_VIRTUAL_BACKGROUND_MODE";
export const SET_VIRTUAL_BACKGROUND_IMAGE = "SET_VIRTUAL_BACKGROUND_IMAGE";
export const SET_VIRTUAL_BACKGROUND_VIDEO = "SET_VIRTUAL_BACKGROUND_VIDEO";
export const GET_MEDIA_DEVICES_SUCCESS = "GET_MEDIA_DEVICES_SUCCESS";
export const GET_MEDIA_DEVICES_FAILED = "GET_MEDIA_DEVICES_FAILED";
export const SET_MICROPHONE_STREAM = "SET_MICROPHONE_STREAM";
export const SET_CAMERA_STREAM = "SET_CAMERA_STREAM";

export const SET_SETTINGS = "SET_SETTINGS";
