export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const WEBEX_BEGIN_API_CALL = "WEBEX_BEGIN_API_CALL";
export const WEBEX_API_CALL_ERROR = "WEBEX_API_CALL_ERROR";
export const WEBEX_API_CALL_SUCCESS = "WEBEX_API_CALL_SUCCESS";

export const WEBEX_LOGIN_SUCCESS = "WEBEX_LOGIN_SUCCESS";
export const WEBEX_LOGIN_FAILED = "WEBEX_LOGIN_FAILED";
export const WEBEX_LOGOUT_SUCCESS = "WEBEX_LOGOUT_SUCCESS";

export const WEBEX_GET_MEETINGS_SUCCESS = "WEBEX_GET_MEETINGS_SUCCESS";
export const WEBEX_GET_MEETINGS_FAILED = "WEBEX_GET_MEETINGS_FAILED";
export const WEBEX_CREATE_MEETING_SUCCESS = "WEBEX_CREATE_MEETING_SUCCESS";
export const WEBEX_CREATE_MEETING_FAILED = "WEBEX_CREATE_MEETING_FAILED";
export const WEBEX_DELETE_MEETING_SUCCESS = "WEBEX_DELETE_MEETING_SUCCESS";
export const WEBEX_DELETE_MEETING_FAILED = "WEBEX_DELETE_MEETING_FAILED";
export const WEBEX_UPDATE_MEETING_SUCCESS = "WEBEX_UPDATE_MEETING_SUCCESS";
export const WEBEX_UPDATE_MEETING_FAILED = "WEBEX_UPDATE_MEETING_FAILED";

export const SET_CONTROL_PANEL = "SET_CONTROL_PANEL";
export const SET_CONTROL_PANEL_ID = "SET_CONTROL_PANEL_ID";
export const SET_CONTROL_PANEL_COMPONENT = "SET_CONTROL_PANEL_COMPONENT";
export const SET_CONTROL_PANEL_CALLBACK = "SET_CONTROL_PANEL_CALLBACK";
export const SET_CONTROL_PANEL_DATA = "SET_CONTROL_PANEL_DATA";
