export const SET_HAND_RAISED = "SET_HAND_RAISED";
export const SET_AUDIO_MUTED = "SET_AUDIO_MUTED";
export const SET_VIDEO_MUTED = "SET_VIDEO_MUTED";
export const SET_UNMUTE_ALLOWED = "SET_UNMUTE_ALLOWED";
export const SET_MEETING_STATUS = "SET_MEETING_STATUS";

export const SET_LOCAL_MEDIA = "SET_LOCAL_MEDIA";
export const SET_REMOTE_MEDIA = "SET_REMOTE_MEDIA";

export const JOIN_MEETING = "JOIN_MEETING";
export const LEAVE_MEETING = "LEAVE_MEETING";

export const SET_ALERT_LEAVE_MEETING = "SET_ALERT_LEAVE_MEETING";
export const SET_OVERLAY = "SET_OVERLAY";

export const SET_CONTROL_PANEL = "SET_CONTROL_PANEL";
export const SET_DTMF_PANEL = "SET_DTMF_PANEL";
